{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "dddf7091",
   "metadata": {},
   "outputs": [],
   "source": [
    "import cadquery as cq\n",
    "\n",
    "# Create a sloped box: 50x50x10, then rotate 20° about X to tilt the top\n",
    "sloped_box = (\n",
    "    cq.Workplane(\"XY\")\n",
    "    .box(50, 50, 10)\n",
    "    .rotate((0, 0, 0), (1, 0, 0), 20)  # rotate around X axis\n",
    ")\n",
    "\n",
    "# Export\n",
    "cq.exporters.export(sloped_box, 'sloped_box.step')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "c1ae2b9d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import cadquery as cq\n",
    "\n",
    "# Create a box at the origin (centered by default)\n",
    "box = cq.Workplane(\"XY\").box(50, 50, 10)  # width, depth, height\n",
    "\n",
    "# Export to a STEP file\n",
    "cq.exporters.export(box, 'box_50x50.step')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "4149f088",
   "metadata": {},
   "outputs": [],
   "source": [
    "model = cq.importers.importStep('box_50x50.step')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "12bdb5ab",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 28%|██▊       | 5/18 [00:52<02:42, 12.48s/it]"
     ]
    }
   ],
   "source": [
    "import cadquery as cq\n",
    "from tqdm import tqdm\n",
    "\n",
    "# Load your sloped STEP file\n",
    "model = cq.importers.importStep(\"est_slopes_less_hard.step\")\n",
    "\n",
    "# Get bounding box\n",
    "bbox = model.val().BoundingBox()\n",
    "xmin, xmax = bbox.xmin, bbox.xmax\n",
    "ymin, ymax = bbox.ymin, bbox.ymax\n",
    "zmin = bbox.zmin  # This is the minimum Z value (bottom of the bounding box)\n",
    "\n",
    "# Parameters\n",
    "COEFFICIENT = 1.0\n",
    "spacing = 4 * COEFFICIENT\n",
    "cone_radius = 4 * COEFFICIENT # FYI: This cannot be bigger than spacing otherwise we get a kernel crash...\n",
    "assert cone_radius <= spacing, \"cone_radius must be less than or equal to spacing to avoid kernel crash\"\n",
    "cone_depth = 4.0 * COEFFICIENT\n",
    "\n",
    "RAISED_DEPTH = 0  # cone_depth / 2\n",
    "connecting_cylinder_radius = 0.75 * COEFFICIENT\n",
    "connecting_cylinder_depth = cone_depth  # 0.5 * cone_depth\n",
    "sphere_radius = 1.5 * COEFFICIENT\n",
    "sphere_depth = connecting_cylinder_depth * 1.5  # (cone_depth + (sphere_radius / 4))\n",
    "\n",
    "# Build divot geometry on the actual 3D surface\n",
    "divots = cq.Workplane(\"XY\")\n",
    "\n",
    "for x in tqdm(range(int(xmin), int(xmax) + 2, int(spacing))):\n",
    "    for y in range(int(ymin), int(ymax) + 2, int(spacing)):\n",
    "        # Create a ray (small box pointing downward) that starts below the object's surface\n",
    "        ray = cq.Solid.makeBox(0.1, 0.1, 100).translate((x, y, zmin - 50))\n",
    "\n",
    "        # Perform intersection to find where the ray meets the surface\n",
    "        intersection = model.intersect(ray)\n",
    "\n",
    "        try:\n",
    "            # Get the highest Z value in the intersected shape\n",
    "            z_top = intersection.val().BoundingBox().zmax\n",
    "\n",
    "            # # Create a cylinder that extends above the surface\n",
    "\n",
    "            # # Create a sphere at the bottom of the cylinder (to round out the divot)\n",
    "            # # Position the sphere so that its center is at the bottom of the cylinder\n",
    "            # sphere = cq.Workplane(\"XY\").sphere(divot_radius).translate((0, 0, -2 * divot_depth))\n",
    "\n",
    "            # # Combine the cylinder and sphere into one shape (cylinder with a spherical bottom)\n",
    "            # divot = cylinder.union(sphere)\n",
    "\n",
    "            # # Create the cone (pointing down)\n",
    "            # cone = cq.Workplane(\"XY\").cone(height=divot_depth, radius1=divot_radius, radius2=0)\n",
    "\n",
    "            # sphere = cq.Workplane(\"XY\").sphere(divot_radius).translate((0, 0, -divot_radius))\n",
    "            top_cylinder = (\n",
    "                cq.Workplane(\"XY\")\n",
    "                .cylinder(cone_depth * 4, cone_radius)\n",
    "                .translate((0, 0, cone_depth * 2 + RAISED_DEPTH))\n",
    "            )  # Extend the cylinder above the surface\n",
    "\n",
    "            cone = (\n",
    "                cq.Workplane(\"XY\")\n",
    "                .circle(cone_radius)\n",
    "                .workplane(offset=-cone_depth)\n",
    "                .center(0, 0)  # make sure it's aligned\n",
    "                .circle(\n",
    "                    0.0001\n",
    "                )  # small non-zero radius instead of 0 to avoid geometry errors\n",
    "                .loft()\n",
    "                .translate((0, 0, RAISED_DEPTH))\n",
    "            )\n",
    "\n",
    "            connecting_cylinder = (\n",
    "                cq.Workplane(\"XY\")\n",
    "                .cylinder(connecting_cylinder_depth, connecting_cylinder_radius)\n",
    "                .translate((0, 0, RAISED_DEPTH - connecting_cylinder_depth))\n",
    "            )\n",
    "\n",
    "            # Create the sphere at the tip\n",
    "            sphere = (\n",
    "                cq.Workplane(\"XY\")\n",
    "                .sphere(sphere_radius)\n",
    "                .translate((0, 0, RAISED_DEPTH - sphere_depth))\n",
    "            )\n",
    "\n",
    "            # Combine them\n",
    "            divot = cone.union(sphere).union(top_cylinder).union(connecting_cylinder)\n",
    "\n",
    "            # Translate the divot to the correct position, starting from the object's surface\n",
    "            divot = divot.translate((x, y, z_top))\n",
    "\n",
    "            # Add to combined divots\n",
    "            divots = divots.union(divot)\n",
    "        except Exception as e:\n",
    "            print(\"skipping divot at ({}, {}): {}\".format(x, y, e))\n",
    "            continue\n",
    "\n",
    "# Subtract divots from original model\n",
    "modified = model.cut(divots)\n",
    "\n",
    "# Export result\n",
    "cq.exporters.export(modified, \"easier_test_slopes_indented.step\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "ethical_necromancy",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
